apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: percona/percona-server:8.0.25
    command:
    - sleep
    - infinity
