// Code generated by MockGen. DO NOT EDIT.
// Source: client/reporter_api/reporter_api_client.go

// Package telemetry is a generated GoMock package.
package telemetry

import (
	reflect "reflect"

	runtime "github.com/go-openapi/runtime"
	gomock "github.com/golang/mock/gomock"
	reporter_api "github.com/percona/percona-server-mysql-operator/pkg/telemetry/client/reporter_api"
)

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// ReporterAPIGenericReport mocks base method.
func (m *MockClientService) ReporterAPIGenericReport(params *reporter_api.ReporterAPIGenericReportParams, opts ...reporter_api.ClientOption) (*reporter_api.ReporterAPIGenericReportOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{params}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReporterAPIGenericReport", varargs...)
	ret0, _ := ret[0].(*reporter_api.ReporterAPIGenericReportOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReporterAPIGenericReport indicates an expected call of ReporterAPIGenericReport.
func (mr *MockClientServiceMockRecorder) ReporterAPIGenericReport(params interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{params}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReporterAPIGenericReport", reflect.TypeOf((*MockClientService)(nil).ReporterAPIGenericReport), varargs...)
}

// SetTransport mocks base method.
func (m *MockClientService) SetTransport(transport runtime.ClientTransport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTransport", transport)
}

// SetTransport indicates an expected call of SetTransport.
func (mr *MockClientServiceMockRecorder) SetTransport(transport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTransport", reflect.TypeOf((*MockClientService)(nil).SetTransport), transport)
}
