// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1ProductFamily ProductFamily represents Percona product family.
//
// swagger:model v1ProductFamily
type V1ProductFamily string

func NewV1ProductFamily(value V1ProductFamily) *V1ProductFamily {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1ProductFamily.
func (m V1ProductFamily) Pointer() *V1ProductFamily {
	return &m
}

const (

	// V1ProductFamilyPRODUCTFAMILYINVALID captures enum value "PRODUCT_FAMILY_INVALID"
	V1ProductFamilyPRODUCTFAMILYINVALID V1ProductFamily = "PRODUCT_FAMILY_INVALID"

	// V1ProductFamilyPRODUCTFAMILYPS captures enum value "PRODUCT_FAMILY_PS"
	V1ProductFamilyPRODUCTFAMILYPS V1ProductFamily = "PRODUCT_FAMILY_PS"

	// V1ProductFamilyPRODUCTFAMILYPXC captures enum value "PRODUCT_FAMILY_PXC"
	V1ProductFamilyPRODUCTFAMILYPXC V1ProductFamily = "PRODUCT_FAMILY_PXC"

	// V1ProductFamilyPRODUCTFAMILYPSMDB captures enum value "PRODUCT_FAMILY_PSMDB"
	V1ProductFamilyPRODUCTFAMILYPSMDB V1ProductFamily = "PRODUCT_FAMILY_PSMDB"

	// V1ProductFamilyPRODUCTFAMILYPBM captures enum value "PRODUCT_FAMILY_PBM"
	V1ProductFamilyPRODUCTFAMILYPBM V1ProductFamily = "PRODUCT_FAMILY_PBM"

	// V1ProductFamilyPRODUCTFAMILYPOSTGRESQL captures enum value "PRODUCT_FAMILY_POSTGRESQL"
	V1ProductFamilyPRODUCTFAMILYPOSTGRESQL V1ProductFamily = "PRODUCT_FAMILY_POSTGRESQL"

	// V1ProductFamilyPRODUCTFAMILYPMM captures enum value "PRODUCT_FAMILY_PMM"
	V1ProductFamilyPRODUCTFAMILYPMM V1ProductFamily = "PRODUCT_FAMILY_PMM"

	// V1ProductFamilyPRODUCTFAMILYEVEREST captures enum value "PRODUCT_FAMILY_EVEREST"
	V1ProductFamilyPRODUCTFAMILYEVEREST V1ProductFamily = "PRODUCT_FAMILY_EVEREST"

	// V1ProductFamilyPRODUCTFAMILYPERCONATOOLKIT captures enum value "PRODUCT_FAMILY_PERCONA_TOOLKIT"
	V1ProductFamilyPRODUCTFAMILYPERCONATOOLKIT V1ProductFamily = "PRODUCT_FAMILY_PERCONA_TOOLKIT"

	// V1ProductFamilyPRODUCTFAMILYPXB captures enum value "PRODUCT_FAMILY_PXB"
	V1ProductFamilyPRODUCTFAMILYPXB V1ProductFamily = "PRODUCT_FAMILY_PXB"
)

// for schema
var v1ProductFamilyEnum []interface{}

func init() {
	var res []V1ProductFamily
	if err := json.Unmarshal([]byte(`["PRODUCT_FAMILY_INVALID","PRODUCT_FAMILY_PS","PRODUCT_FAMILY_PXC","PRODUCT_FAMILY_PSMDB","PRODUCT_FAMILY_PBM","PRODUCT_FAMILY_POSTGRESQL","PRODUCT_FAMILY_PMM","PRODUCT_FAMILY_EVEREST","PRODUCT_FAMILY_PERCONA_TOOLKIT","PRODUCT_FAMILY_PXB"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1ProductFamilyEnum = append(v1ProductFamilyEnum, v)
	}
}

func (m V1ProductFamily) validateV1ProductFamilyEnum(path, location string, value V1ProductFamily) error {
	if err := validate.EnumCase(path, location, value, v1ProductFamilyEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 product family
func (m V1ProductFamily) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1ProductFamilyEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 product family based on context it is used
func (m V1ProductFamily) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
