apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    percona.com/last-config-hash: 0cfb3876e17fee4594701a3aaef9d203
  creationTimestamp: "2023-03-01T08:42:23Z"
  generation: 1
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: config-router
    app.kubernetes.io/managed-by: percona-server-operator
    app.kubernetes.io/name: percona-server
    app.kubernetes.io/part-of: percona-server
  name: config-router-mysql
  namespace: kuttl-test-fluent-vulture
  ownerReferences:
  - apiVersion: ps.percona.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: PerconaServerMySQL
    name: config-router
    uid: 6c7ec338-2dd1-4693-879d-cb55297afc12
  resourceVersion: "17997"
  uid: c8fcca92-e97d-4dcb-94a9-24a219049fa9
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
      app.kubernetes.io/instance: config-router
      app.kubernetes.io/managed-by: percona-server-operator
      app.kubernetes.io/name: percona-server
      app.kubernetes.io/part-of: percona-server
  serviceName: config-router-mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mysql
        app.kubernetes.io/instance: config-router
        app.kubernetes.io/managed-by: percona-server-operator
        app.kubernetes.io/name: percona-server
        app.kubernetes.io/part-of: percona-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: mysql
                app.kubernetes.io/instance: config-router
                app.kubernetes.io/managed-by: percona-server-operator
                app.kubernetes.io/name: percona-server
                app.kubernetes.io/part-of: percona-server
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - mysqld
        command:
        - /opt/percona/ps-entrypoint.sh
        env:
        - name: MONITOR_HOST
          value: '%'
        - name: SERVICE_NAME
          value: config-router-mysql
        - name: SERVICE_NAME_UNREADY
          value: config-router-mysql-unready
        - name: CLUSTER_HASH
          value: "2944336"
        - name: CR_UID
          value: 6c7ec338-2dd1-4693-879d-cb55297afc12
        - name: CLUSTER_TYPE
          value: group-replication
        image: perconalab/percona-server-mysql-operator:main-psmysql
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /opt/percona/healthcheck
            - liveness
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 33062
          name: mysql-admin
          protocol: TCP
        - containerPort: 33060
          name: mysqlx
          protocol: TCP
        - containerPort: 33061
          name: mysql-gr
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/percona/healthcheck
            - readiness
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        startupProbe:
          exec:
            command:
            - /opt/percona/bootstrap
          failureThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 300
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/percona
          name: bin
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/mysql/mysql-users-secret
          name: users
        - mountPath: /etc/mysql/mysql-tls-secret
          name: tls
        - mountPath: /etc/mysql/config
          name: config
      - command:
        - /opt/percona/sidecar
        image: perconalab/percona-server-mysql-operator:main-backup
        imagePullPolicy: Always
        name: xtrabackup
        ports:
        - containerPort: 6033
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/percona
          name: bin
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/mysql/mysql-users-secret
          name: users
        - mountPath: /var/log/xtrabackup
          name: backup-logs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /opt/percona-server-mysql-operator/ps-init-entrypoint.sh
        image: perconalab/percona-server-mysql-operator:k8sps-217-custom-router-config
        imagePullPolicy: Always
        name: mysql-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/percona
          name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: bin
      - name: users
        secret:
          defaultMode: 420
          secretName: internal-config-router
      - name: tls
        secret:
          defaultMode: 420
          secretName: test-ssl
      - name: config
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: my.cnf
                path: my-config.cnf
              name: config-router-mysql
              optional: true
          - configMap:
              items:
              - key: my.cnf
                path: auto-config.cnf
              name: auto-config-router-mysql
              optional: true
          - secret:
              items:
              - key: my.cnf
                path: my-secret.cnf
              name: config-router-mysql
              optional: true
      - emptyDir: {}
        name: backup-logs
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2G
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: config-router-mysql-6d4d4fb9c
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: config-router-mysql-6d4d4fb9c
  updatedReplicas: 3
