apiVersion: ps.percona.com/v1
kind: PerconaServerMySQLBackup
metadata:
  finalizers:
    - percona.com/delete-backup
  name: backup1
spec:
  clusterName: ps-cluster1
  storageName: minio
#  sourcePod: ps-cluster1-mysql-1
#  containerOptions:
#    env:
#      - name: CUSTOM_VAR
#        value: "false"
#    args:
#      xbcloud:
#        - --someflag=abc
#      xbstream:
#        - --someflag=abc
#      xtrabackup:
#        - --someflag=abc
