apiVersion: ps.percona.com/v1
kind: PerconaServerMySQLRestore
metadata:
  name: restore1
spec:
  clusterName: ps-cluster1
  backupName: backup1
#  containerOptions:
#    env:
#      - name: CUSTOM_VAR
#        value: "false"
#    args:
#      xbcloud:
#        - --someflag=abc
#      xbstream:
#        - --someflag=abc
#      xtrabackup:
#        - --someflag=abc
#  backupSource:
#    destination: s3://S3-BACKUP-BUCKET-NAME-HERE/backup-path
#    storage:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kubernetes.io/e2e-az-name
#                    operator: In
#                    values:
#                      - e2e-az1
#                      - e2e-az2
#      annotations:
#        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
#        service.beta.kubernetes.io/aws-load-balancer-type: nlb
#      containerOptions:
#        args:
#          xbcloud:
#            - --someflag=abc
#          xbstream:
#            - --someflag=abc
#          xtrabackup:
#            - --someflag=abc
#        env:
#          - name: CUSTOM_VAR
#            value: "false"
#      containerSecurityContext:
#        privileged: false
#        runAsGroup: 1001
#        runAsUser: 1001
#      labels:
#        rack: rack-22
#      nodeSelector:
#        topology.kubernetes.io/zone: us-east-1a
#      podSecurityContext:
#        fsGroup: 1001
#        supplementalGroups:
#          - 1001
#          - 1002
#          - 1003
#      priorityClassName: high-priority
#      resources:
#        limits:
#          cpu: 100m
#          memory: 100M
#        requests:
#          cpu: 200m
#          memory: 200M
#      runtimeClassName: image-rc
#      s3:
#        bucket: S3-BACKUP-BUCKET-NAME-HERE
#        credentialsSecret: ps-cluster1-s3-credentials
#        endpointUrl: https://s3.amazonaws.com
#        prefix: PREFIX_NAME
#        region: us-west-2
#      schedulerName: default-scheduler
#      tolerations:
#        - effect: NoExecute
#          key: node.alpha.kubernetes.io/unreachable
#          operator: Exists
#          tolerationSeconds: 6000
#      topologySpreadConstraints:
#        - labelSelector:
#            matchLabels:
#              app.kubernetes.io/name: percona-server
#          maxSkew: 1
#          topologyKey: kubernetes.io/hostname
#          whenUnsatisfiable: DoNotSchedule
#      type: s3
#      verifyTLS: true
#      volumeSpec:
#        emptyDir: {}
#        hostPath:
#          path: /data
#          type: Directory
#        persistentVolumeClaim:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 2Gi
#          storageClassName: standard
