---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: percona-server-mysql-operator-orchestrator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaservermysqls
  verbs:
  - get
