apiVersion: ps.percona.com/v1
kind: PerconaServerMySQLBackup
metadata:
  name: backup1
  finalizers:
    - percona.com/delete-backup
spec:

#  sourceHost: cluster1-mysql-0.<mysql_service_name>.<namespace>
  clusterName: ps-cluster1
  storageName: minio
