apiVersion: ps.percona.com/v1alpha1
kind: PerconaServerMySQLBackup
metadata:
  name: backup1
  finalizers:
    - percona.com/delete-backup
spec:
  clusterName: ps-cluster1
  storageName: minio
#  sourceHost: ps-cluster1-mysql-0.ps-cluster1-mysql.<namespace>
#  containerOptions:
#    env:
#    - name: VERIFY_TLS
#      value: "false"
#    args:
#      xtrabackup:
#      - "--someflag=abc"
#      xbcloud:
#      - "--someflag=abc"
#      xbstream:
#      - "--someflag=abc"
