apiVersion: v1
kind: Secret
metadata:
  name: ps-cluster1-binlog-server-keyring
stringData:
  keyring.json: |-
    {
      "version": 1,
      "keys": [
        {
          "id": "alpha",
          "cipher": "AES-128-ECB",
          "data_hex": "3a846b8862e7f2d24a3523c8928a51b8"
        }
      ]
    }


