apiVersion: ps.percona.com/v1
kind: PerconaServerMySQLClusterSet
metadata:
  name: my-cluster-set
spec:
  primaryCluster: pscluster1
  credentialsSecret:
    name: ps-cluster1-secrets
    key: root
  allowForcedFailover: false
  clusters:
    - name: pscluster1
      endpoints:
      - host: 34.118.226.200
  mysqlShellRunner:
    image: perconalab/percona-server-mysql-operator:main-psmysql8.4