apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-server-for-mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: percona-server-for-mysql-operator-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: percona-server-for-mysql-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlbackups
  - perconaserverformysqlbackups/finalizers
  - perconaserverformysqlbackups/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlrestores
  - perconaserverformysqlrestores/finalizers
  - perconaserverformysqlrestores/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqls
  - perconaserverformysqls/finalizers
  - perconaserverformysqls/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-for-mysql-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-for-mysql-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: percona-server-for-mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-for-mysql-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-for-mysql-operator-role
subjects:
- kind: ServiceAccount
  name: percona-server-for-mysql-operator
---
