apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-server-mysql-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-server-mysql-operator-orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: percona-server-mysql-operator-leaderelection
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: percona-server-mysql-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  - certmanager.k8s.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaservermysqlbackups
  - perconaservermysqlbackups/finalizers
  - perconaservermysqlbackups/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaservermysqlrestores
  - perconaservermysqlrestores/finalizers
  - perconaservermysqlrestores/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaservermysqls
  - perconaservermysqls/finalizers
  - perconaservermysqls/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: percona-server-mysql-operator-orchestrator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaservermysqls
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-mysql-operator-leaderelection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-mysql-operator-leaderelection
subjects:
- kind: ServiceAccount
  name: percona-server-mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-mysql-operator
subjects:
- kind: ServiceAccount
  name: percona-server-mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-mysql-operator-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-mysql-operator-orchestrator
subjects:
- kind: ServiceAccount
  name: percona-server-mysql-operator-orchestrator
---
