apiVersion: ps.percona.com/v1
kind: PerconaServerMySQLRestore
metadata:
  name: restore1
spec:
  clusterName: ps-cluster1
  backupName: backup1
#  containerOptions:
#    env:
#    - name: VERIFY_TLS
#      value: "false"
#    args:
#      xtrabackup:
#      - "--someflag=abc"
#      xbcloud:
#      - "--someflag=abc"
#      xbstream:
#      - "--someflag=abc"
#  backupSource:
#    destination: s3://S3-BACKUP-BUCKET-NAME-HERE/backup-path
#    storage:
#      s3:
#        bucket: S3-BACKUP-BUCKET-NAME-HERE
#        credentialsSecret: cluster1-s3-credentials
#        region: us-west-2
#      type: s3
