apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitor_password
  clustercheck: clustercheck_password
  pmmserver: admin
  operator: operator_password
  replication: replication_password
  orchestrator: orchestrator_password
