#!/bin/bash

set -e

exec 5>&2
export BASH_XTRACEFD="5"

ROOT_REPO=${ROOT_REPO:-${PWD}}
source "${ROOT_REPO}/e2e-tests/vars.sh"

BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git rev-parse HEAD)
IMAGE=${IMAGE/#percona\//perconalab/}
DOCKER_DEFAULT_PLATFORM=${DOCKER_DEFAULT_PLATFORM:-"linux/amd64"}

build_options='--squash'
if [[ ${DOCKER_SQUASH} == 0 ]]; then
	build_options=''
fi
if [[ ${DOCKER_NOCACHE:-0} == 1 ]]; then
	build_options="$build_options --no-cache"
fi

build_operator() {
	if [ "${RELEASE:-1}" = 0 ]; then
		GO_LDFLAGS="-race"
	fi

	export IMAGE
	export DOCKER_DEFAULT_PLATFORM
	export GO_LDFLAGS="-w -s -trimpath $GO_LDFLAGS"
	pushd "${ROOT_REPO}" || exit

	build_command='build'
	if echo "$DOCKER_DEFAULT_PLATFORM" | grep -q ','; then
		build_command='buildx build'
		build_options="$build_options --push=true"
		if [ "${DOCKER_PUSH:-1}" = 0 ]; then
			echo "'docker $build_command' doesn't support DOCKER_PUSH=0 option in case of multi-arch builds, please use DOCKER_PUSH=1"
			exit 1
		fi
	fi

	docker $build_command \
		--platform $DOCKER_DEFAULT_PLATFORM \
		--build-arg GIT_COMMIT=$GIT_COMMIT \
		--build-arg GIT_BRANCH=$GIT_BRANCH \
		--build-arg BUILD_TIME=$BUILD_TIME \
		--build-arg GO_LDFLAGS="$GO_LDFLAGS" \
		--progress plain \
		$build_options \
		-t "${IMAGE}" -f build/Dockerfile .
	popd

	if [ "${DOCKER_PUSH:-1}" = 1 ] && [[ $build_command == 'build' ]]; then
		docker push ${IMAGE}
	fi

}

if [[ $BUILD == "0" ]]; then
	exit 0
fi

# wait for docker
until docker info >/dev/null; do sleep 1; done

build_operator
