// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	clusterset "github.com/percona/percona-server-mysql-operator/pkg/clusterset"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/percona/percona-server-mysql-operator/api/v1"
)

// ClusterSetManager is an autogenerated mock type for the ClusterSetManager type
type ClusterSetManager struct {
	mock.Mock
}

// CreateClusterSet provides a mock function with given fields: ctx, clustersetName, sslMode
func (_m *ClusterSetManager) CreateClusterSet(ctx context.Context, clustersetName string, sslMode v1.ClusterSetSSLMode) error {
	ret := _m.Called(ctx, clustersetName, sslMode)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.ClusterSetSSLMode) error); ok {
		r0 = rf(ctx, clustersetName, sslMode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForcePrimaryCluster provides a mock function with given fields: ctx, clusterName
func (_m *ClusterSetManager) ForcePrimaryCluster(ctx context.Context, clusterName string) error {
	ret := _m.Called(ctx, clusterName)

	if len(ret) == 0 {
		panic("no return value specified for ForcePrimaryCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Status provides a mock function with given fields: ctx
func (_m *ClusterSetManager) Status(ctx context.Context) (clusterset.Status, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 clusterset.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (clusterset.Status, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) clusterset.Status); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(clusterset.Status)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClusterSetManager creates a new instance of ClusterSetManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterSetManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterSetManager {
	mock := &ClusterSetManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
