// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// EventRecorder is an autogenerated mock type for the EventRecorder type
type EventRecorder struct {
	mock.Mock
}

// Eventf provides a mock function with given fields: regarding, related, eventtype, reason, action, note, args
func (_m *EventRecorder) Eventf(regarding runtime.Object, related runtime.Object, eventtype string, reason string, action string, note string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, regarding, related, eventtype, reason, action, note)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewEventRecorder creates a new instance of EventRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRecorder {
	mock := &EventRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
