// Code generated by go-swagger; DO NOT EDIT.

package reporter_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/percona/percona-server-mysql-operator/pkg/telemetry/client/models"
)

// NewReporterAPIGenericReportParams creates a new ReporterAPIGenericReportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReporterAPIGenericReportParams() *ReporterAPIGenericReportParams {
	return &ReporterAPIGenericReportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReporterAPIGenericReportParamsWithTimeout creates a new ReporterAPIGenericReportParams object
// with the ability to set a timeout on a request.
func NewReporterAPIGenericReportParamsWithTimeout(timeout time.Duration) *ReporterAPIGenericReportParams {
	return &ReporterAPIGenericReportParams{
		timeout: timeout,
	}
}

// NewReporterAPIGenericReportParamsWithContext creates a new ReporterAPIGenericReportParams object
// with the ability to set a context for a request.
func NewReporterAPIGenericReportParamsWithContext(ctx context.Context) *ReporterAPIGenericReportParams {
	return &ReporterAPIGenericReportParams{
		Context: ctx,
	}
}

// NewReporterAPIGenericReportParamsWithHTTPClient creates a new ReporterAPIGenericReportParams object
// with the ability to set a custom HTTPClient for a request.
func NewReporterAPIGenericReportParamsWithHTTPClient(client *http.Client) *ReporterAPIGenericReportParams {
	return &ReporterAPIGenericReportParams{
		HTTPClient: client,
	}
}

/*
ReporterAPIGenericReportParams contains all the parameters to send to the API endpoint

	for the reporter API generic report operation.

	Typically these are written to a http.Request.
*/
type ReporterAPIGenericReportParams struct {

	// Body.
	Body *models.V1ReportRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reporter API generic report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReporterAPIGenericReportParams) WithDefaults() *ReporterAPIGenericReportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reporter API generic report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReporterAPIGenericReportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) WithTimeout(timeout time.Duration) *ReporterAPIGenericReportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) WithContext(ctx context.Context) *ReporterAPIGenericReportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) WithHTTPClient(client *http.Client) *ReporterAPIGenericReportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) WithBody(body *models.V1ReportRequest) *ReporterAPIGenericReportParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the reporter API generic report params
func (o *ReporterAPIGenericReportParams) SetBody(body *models.V1ReportRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ReporterAPIGenericReportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
