// Code generated by go-swagger; DO NOT EDIT.

package reporter_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/percona/percona-server-mysql-operator/pkg/telemetry/client/models"
)

// ReporterAPIGenericReportReader is a Reader for the ReporterAPIGenericReport structure.
type ReporterAPIGenericReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReporterAPIGenericReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReporterAPIGenericReportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewReporterAPIGenericReportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReporterAPIGenericReportOK creates a ReporterAPIGenericReportOK with default headers values
func NewReporterAPIGenericReportOK() *ReporterAPIGenericReportOK {
	return &ReporterAPIGenericReportOK{}
}

/*
ReporterAPIGenericReportOK describes a response with status code 200, with default header values.

A successful response.
*/
type ReporterAPIGenericReportOK struct {
	Payload models.V1ReportResponse
}

// IsSuccess returns true when this reporter Api generic report o k response has a 2xx status code
func (o *ReporterAPIGenericReportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reporter Api generic report o k response has a 3xx status code
func (o *ReporterAPIGenericReportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reporter Api generic report o k response has a 4xx status code
func (o *ReporterAPIGenericReportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reporter Api generic report o k response has a 5xx status code
func (o *ReporterAPIGenericReportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reporter Api generic report o k response a status code equal to that given
func (o *ReporterAPIGenericReportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reporter Api generic report o k response
func (o *ReporterAPIGenericReportOK) Code() int {
	return 200
}

func (o *ReporterAPIGenericReportOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/telemetry/GenericReport][%d] reporterApiGenericReportOK %s", 200, payload)
}

func (o *ReporterAPIGenericReportOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/telemetry/GenericReport][%d] reporterApiGenericReportOK %s", 200, payload)
}

func (o *ReporterAPIGenericReportOK) GetPayload() models.V1ReportResponse {
	return o.Payload
}

func (o *ReporterAPIGenericReportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReporterAPIGenericReportDefault creates a ReporterAPIGenericReportDefault with default headers values
func NewReporterAPIGenericReportDefault(code int) *ReporterAPIGenericReportDefault {
	return &ReporterAPIGenericReportDefault{
		_statusCode: code,
	}
}

/*
ReporterAPIGenericReportDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ReporterAPIGenericReportDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this reporter API generic report default response has a 2xx status code
func (o *ReporterAPIGenericReportDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this reporter API generic report default response has a 3xx status code
func (o *ReporterAPIGenericReportDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this reporter API generic report default response has a 4xx status code
func (o *ReporterAPIGenericReportDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this reporter API generic report default response has a 5xx status code
func (o *ReporterAPIGenericReportDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this reporter API generic report default response a status code equal to that given
func (o *ReporterAPIGenericReportDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the reporter API generic report default response
func (o *ReporterAPIGenericReportDefault) Code() int {
	return o._statusCode
}

func (o *ReporterAPIGenericReportDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/telemetry/GenericReport][%d] ReporterAPI_GenericReport default %s", o._statusCode, payload)
}

func (o *ReporterAPIGenericReportDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/telemetry/GenericReport][%d] ReporterAPI_GenericReport default %s", o._statusCode, payload)
}

func (o *ReporterAPIGenericReportDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ReporterAPIGenericReportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
