apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 300
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: semi-sync-mysql
status:
  observedGeneration: 1
  replicas: 3
  readyReplicas: 3
  currentReplicas: 3
  updatedReplicas: 3
  collisionCount: 0
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: semi-sync-orc
status:
  observedGeneration: 1
  replicas: 1
  readyReplicas: 1
  currentReplicas: 1
  updatedReplicas: 1
  collisionCount: 0
