# https://olm.operatorframework.io/docs/concepts/crds/clusterserviceversion/
# https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html
# https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/creating-the-csv
# https://pkg.go.dev/github.com/operator-framework/api@v0.10.1/pkg/operators/v1alpha1#ClusterServiceVersion
---
apiVersion: operators.coreos.com/v1
kind: ClusterServiceVersion
metadata:
  name: ''
  namespace: default
  annotations:
    support: Percona
    # The following affect how the package is indexed at OperatorHub.io:
    # https://operatorhub.io/?category=Database
    # https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/
    categories: Database
    capabilities: Full Lifecycle
    certified: 'true'
    description: >-
      Percona Operator for MySQL based on Percona Server for MySQL automates the creation and management of highly available, enterprise-ready MySQL database clusters on Kubernetes.
    # The following appear on the details page at OperatorHub.io:
    createdAt: "%Y-%m-%dT%H:%M:%S.%3Z"
    repository: 'https://github.com/percona/percona-server-mysql-operator'
    alm-examples: ""
spec:
  # The following affect how the package is indexed at OperatorHub.io:
  # https://operatorhub.io/
  displayName: Percona Operator for MySQL based on Percona Server for MySQL
  provider:
    # These values become labels on the PackageManifest.
    name: Percona
    url: https://www.percona.com/
  labels: {}
  keywords:
    - mysql
    - percona
    - database
    - sql
    - operator
    - group-replication
    - asynchronous-replication
  # The following appear on the details page at OperatorHub.io:
  # https://operatorhub.io/operator/percona-server-mysql-operator
  description: |2-
    ## Percona is Cloud Native

    Percona Operator for MySQL based on Percona Server for MySQL follows our best
    practices for deployment and configuration of highly-available, fault-tolerant
    MySQL instances in a Kubernetes-based environment on-premises or in the cloud.
    It provides the following capabilities:


    * Deploy group replication MySQL clusters with HAProxy or MySQL Router

    * Deploy asynchronous replication MySQL clusters with Orchestrator and HAProxy

    * Expose clusters with regular Kubernetes Services

    * Monitor the cluster with Percona Monitoring and Management

    * Customize MySQL configuration

    * Manage system user passwords


    Consult the
    [documentation](https://docs.percona.com/percona-operator-for-mysql/ps/)
    on the Percona Operator for MySQL based on Percona Server for MySQL for complete
    details on capabilities and options.


    ### Supported Features


    * **Scale Your Cluster**  change the `size` parameter to add or remove
    members of the cluster. Three is the minimum recommended size for a
    functioning cluster.


    * **Manage Your Users**  add, remove, or
    change the privileges of database users


    * **Automate Your Backups**  configure cluster backups to run on a
    scheduled basis. Backups can be stored on a persistent volume or
    S3-compatible storage.


    * **Proxy integration**  choose HAProxy or MySQL Router as a proxy in front of
    the MySQL cluster. Proxies are deployed and configured automatically
    with the Operator.


    ### Common Configurations


    * **Set Resource Limits** - set limitation on requests to CPU and memory
    resources.


    * **Customize Storage** - set the desired Storage Class and Access Mode for
    your database cluster data.


    * **Control Scheduling** - define how your MySQL Pods are scheduled onto the
    K8S cluster with tolerations, pod disruption budgets, node selector and
    affinity settings.

    * Group Replication and Asynchronous Replication support

    * HAProxy and MySQL Router support

    * MySQL Orchestrator for asynchronous replication topology management

    * Fully automated minor version updates (Smart Update)

    * Support MySQL versions 8.0 and 8.4

    ### Before You Start


    Add the MySQL user `Secret` to Kubernetes. User information must be placed in
    the data section of the `secrets.yaml`

    file with Base64-encoded logins and passwords for the user accounts.


    Below is a sample `secrets.yaml` file for the correct formatting.


    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: ps-cluster1-secrets
    type: Opaque
    data:
      root: cm9vdF9wYXNzd29yZA==
      xtrabackup: YmFja3VwX3Bhc3N3b3Jk
      monitor: bW9uaXRvcg==
      clustercheck: Y2x1c3RlcmNoZWNrcGFzc3dvcmQ=
      proxyadmin: YWRtaW5fcGFzc3dvcmQ=
      pmmserver: c3VwYXxefHBheno=
      operator: b3BlcmF0b3JhZG1pbg==
      orchestrator: b3JjaGVzdHJhdG9yX3Bhc3N3b3Jk
      replication: cmVwbF9wYXNzd29yZAo=
    ```
  version:
  links:
    - name: Percona
      url: 'https://www.percona.com/'
    - name: Cloud Native Landing Page
      url: 'https://www.percona.com/cloud-native/'
    - name: Documentation
      url: 'https://docs.percona.com/percona-operator-for-mysql/ps/'
    - name: Github
      url: 'https://github.com/percona/percona-server-mysql-operator'
  maintainers:
    - name: Percona
      email: info@percona.com
  icon:
    - base64data: >-
        PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTGF5ZXJfMTIiIGRhdGEtbmFtZT0iTGF5ZXIgMTIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDExMjMuNTEgMTEyMy41MSI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgZmlsbDogIzJhYTZkZjsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2RlZnM+CiAgPGcgaWQ9IkJhY2tncm91bmQiPgogICAgPGc+CiAgICAgIDxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTEwNzkuNzksMTAxMC44OUg0My43MUw1NjEuNzUsMTEzLjYybDUxOC4wNCw4OTcuMjdaTTcyLjAzLDk5NC41NGg5NzkuNDRMNTYxLjc1LDE0Ni4zMiw3Mi4wMyw5OTQuNTRaIi8+CiAgICAgIDxnPgogICAgICAgIDxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTI4NS40Niw4MTUuMzFsMzEuMDIsODIuNjNoNDUyLjU2bDY4LjU4LTgyLjYzSDI4NS40NloiLz4KICAgICAgICA8cG9seWxpbmUgY2xhc3M9ImNscy0xIiBwb2ludHM9IjMzOC41OCA3ODYuMjQgNDg1LjI0IDUyOC41MiA1MDQuNzggNTYyLjI2IDM3Ni45MyA3ODYuMjQiLz4KICAgICAgICA8cG9seWdvbiBjbGFzcz0iY2xzLTEiIHBvaW50cz0iNjA3LjExIDcwNi40MyA2NTMuMTkgNzg2LjI0IDgwMS4zOSA3ODYuMjQgNjA3LjExIDQ0OS43NCA0MTIuODMgNzg2LjI0IDU2MS4wMyA3ODYuMjQgNjA3LjExIDcwNi40MyIvPgogICAgICAgIDxwb2x5Z29uIGNsYXNzPSJjbHMtMSIgcG9pbnRzPSI0NzEuNjUgNDQ5Ljc0IDUyMS4wOSA1MzUuMzggNTcwLjU0IDQ0OS43NCA0NzEuNjUgNDQ5Ljc0Ii8+CiAgICAgIDwvZz4KICAgIDwvZz4KICA8L2c+Cjwvc3ZnPg==
      mediatype: image/svg+xml
  customresourcedefinitions:
    owned:
      - description: Instance of a Percona Server for MySQL
        displayName: PerconaServerMySQL
        kind: PerconaServerMySQL
        name: perconaservermysqls.ps.percona.com
        version: v1
        specDescriptors: []
        statusDescriptors: []
      - description: Instance of a Percona Server for MySQL Backup
        displayName: PerconaServerMySQLBackup
        kind: PerconaServerMySQLBackup
        name: perconaservermysqlbackups.ps.percona.com
        version: v1
        specDescriptors: []
        statusDescriptors: []
      - description: Instance of a Percona Server for MySQL Restore
        displayName: PerconaServerMySQLRestore
        kind: PerconaServerMySQLRestore
        name: perconaservermysqlrestores.ps.percona.com
        version: v1
        specDescriptors: []
        statusDescriptors: []
      - description: Instance of a Percona Server for MySQL ClusterSet
        displayName: PerconaServerMySQLClusterSet
        kind: PerconaServerMySQLClusterSet
        name: perconaservermysqlclustersets.ps.percona.com
        version: v1
        specDescriptors: []
        statusDescriptors: []
    required: []
  # https://olm.operatorframework.io/docs/best-practices/common/
  # Note: The minKubeVersion must correspond to the lowest supported OCP version
  maturity: stable
  # https://olm.operatorframework.io/docs/advanced-tasks/operator-scoping-with-operatorgroups/
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      permissions:
      deployments:
