// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	rest "k8s.io/client-go/rest"

	v1 "k8s.io/api/core/v1"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, pod, containerName, command, stdin, stdout, stderr, tty
func (_m *Client) Exec(ctx context.Context, pod *v1.Pod, containerName string, command []string, stdin io.Reader, stdout io.Writer, stderr io.Writer, tty bool) error {
	ret := _m.Called(ctx, pod, containerName, command, stdin, stdout, stderr, tty)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Pod, string, []string, io.Reader, io.Writer, io.Writer, bool) error); ok {
		r0 = rf(ctx, pod, containerName, command, stdin, stdout, stderr, tty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// REST provides a mock function with no fields
func (_m *Client) REST() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for REST")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
