# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/ps.percona.com_perconaservermysqls.yaml
- bases/ps.percona.com_perconaservermysqlbackups.yaml
- bases/ps.percona.com_perconaservermysqlrestores.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/versionlabel_in_perconaserverformysql.yaml
- patches/versionlabel_in_perconaserverformysqlbackups.yaml
- patches/versionlabel_in_perconaserverformysqlrestores.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
