apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 30
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: 05-check-orchestrator
data:
  cluster: init-deploy-mysql-0.init-deploy-mysql:3306
  instances: |
    init-deploy-mysql-0.init-deploy-mysql
    init-deploy-mysql-1.init-deploy-mysql
    init-deploy-mysql-2.init-deploy-mysql
