apiVersion: kuttl.dev/v1beta1
kind: TestStep
timeout: 30
commands:
- script: |
    . ../functions
    set -o errexit
    set -o xtrace

    orc_host=$(get_orc_headless_fqdn $(get_cluster_name) 0)
    cluster=$(run_curl "http://${orc_host}:3000/api/clusters/" | jq -r .[0] | sed "s/.${NAMESPACE}//g")
    args="--from-literal=cluster=${cluster}"

    run_curl "http://${orc_host}:3000/api/cluster/${cluster}/" | jq -r .[].Key.Hostname | sed "s/.${NAMESPACE}//g" > "${tmp_dir}/instances"
    args="${args} --from-file=instances=${tmp_dir}/instances"

    kubectl create configmap -n "${NAMESPACE}" 05-check-orchestrator ${args}
