apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    . ../functions
    set -o errexit
    set -o xtrace

    helm install monitoring \
      -n "${NAMESPACE}" \
      --set platform=kubernetes \
      https://percona-charts.storage.googleapis.com/pmm-server-2.23.0.tgz

  timeout: 30
