{{/* vim: filetype=gotmpl */}}
{{- define "main" -}}
{{ "{{/* vim: filetype=helm */}}" }}
{{ "{{/* AUTOGENERATED FILE — DO NOT EDIT */}}\n" }}
{{- range $m := .Members }}
  {{- template "member" (list $m 0 "") }}
{{- end }}
{{- end -}}

{{- define "member" -}}
{{- $field  := index . 0 -}}
{{- $depth  := index . 1 -}}
{{- $prefix := index . 2 -}}
{{- $width  := mul $depth 2 -}}
{{- $pad    := printf "%*s" $width "" -}}

{{- $path := $field.Name -}}
{{- if and (ne $prefix "") -}}
  {{- $path = printf "%s.%s" $prefix $field.Name -}}
{{- end -}}

{{- if and (ne $width 0) (not (helmIsRequired $field)) -}}
  {{- printf "%s" $pad -}}
  {{- printf "{{- if .Values.%s }}\n" (trimPrefix "spec." $path) -}}
{{- end -}}

{{- printf "%s%s: " $pad $field.Name -}}

{{- if ne (helmCustomValue $path) "" }}
  {{- helmCustomValue $path -}}{{- printf "\n" -}}
{{- else -}}
  {{- if helmShouldRenderInner $field.Type }}
    {{- printf "\n" -}}
    {{- range $child := $field.Type.Members }}
      {{- template "member" (list $child (add $depth 1) $path) }}
    {{- end }}
  {{- else }}
      {{- if gt (len $field.Type.Members) 0 }}
        {{- $innerPad    := printf "%*s" (add $width 2) "" -}}
        {{- if eq $prefix "" -}}
          {{- printf "\n%s{{- .Values.%s | toYaml | nindent %d }}\n" $innerPad (trimPrefix "spec." $path) $width -}}
        {{- else -}}
          {{- printf "\n%s{{- .Values.%s | toYaml | nindent %d }}\n" $innerPad (trimPrefix "spec." $path) (add $width 2) -}}
        {{- end -}}
      {{- else -}}
        {{- printf "{{ .Values.%s }}\n" (trimPrefix "spec." $path) -}}
        {{- if and (ne $width 0) (not (helmIsRequired $field)) (ne (helmDefault $path) "") -}}
          {{- printf "%s{{- else }}\n" $pad -}}
          {{- printf "%s%s: %s\n" $pad $field.Name (helmDefault $path) -}}
        {{- end -}}
      {{- end -}}
  {{- end -}}
{{- end -}}

{{- if and (ne $width 0) (not (helmIsRequired $field)) -}}
  {{- printf "%s" $pad -}}
  {{- printf "{{- end }}\n" -}}
{{- end -}}

{{- end -}}

