name: Integration tests

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  # push:
  pull_request:

jobs:
  test:
    name: Env Test
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    #       - macos-latest
    # needs: check_docs_only
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    # if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && needs.check_docs_only.outputs.skip != 'true'
    steps:
      # - name: Clone the code
      #   uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      # This step is needed as the following one tries to remove
      # kustomize for each test but has no permission to do so
      # - name: Remove pre-installed kustomize
      #   run: sudo rm -f /usr/local/bin/kustomize
      - name: Perform the test
        run: make test
      # - name: Report failure
      #   uses: nashmaniac/create-issue-action@v1.1
      #   # Only report failures of pushes (PRs have are visible through the Checks section) to the default branch
      #   if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   with:
      #     title: 🐛 Unit tests failed on ${{ matrix.os }} for ${{ github.sha }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: kind/bug
      #     body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}